### PR TITLE
Avoid array 'tmap->tasks[32]' accessed at index 32, which is out of bounds.

### PR DESCRIPTION
**Pull request by manux81**
Found by cppcheck tool

### CODE REVIEW

**Comment by jermar** [comment]
On line 260 there is a check, which will not allow index 32 to be accessed. The construction is a little weird but allows to print an error message if there are too many tasks and halt.

**Comment by Dzejrou** [comment]
> On line 260 there is a check, which will not allow index 32 to be accessed. The construction is a little weird but allows to print an error message if there are too many tasks and halt.

This means the check is performed on every iteration, does it not? What about if the control variable was declared before the for loop that uses it and the check is moved after the loop ends? This way we do not check it on each iteration, we do not risk anything due to the lax for loop condition (I'm not saying there are hidden bugs, but future modifications of the loop can easily introduce them because of this) and we conform with the check. All that at no real price, what do you think? (The for loop is at the end of the scope, so there should not be problems with the control variable having its scope extended, but even so an artificial scope would help there.)

**Comment by le-jzr** [comment]
@Dzejrou That would mean duplicating most of the loop, and comparing two integers is insignificant relative to the other stuff.

@manux81 As @jermar said, the original code is correct, if a bit confusing. The condition of for loop is redundant. Isn't there any way to tell cppcheck that `halt()` never returns? It's already marked such by a GNU attribute, so I'm confused as to why it doesn't understand that.

**Comment by manux81** [comment]
Flow control check needs a loop break after halt function is called to disable error (I already tried and it works) but we can considerate as false positive.

**Comment by le-jzr** [comment]
If we do that, some other tool might report the break as dead code. :) I think we can close this for now. Maybe later versions of cppcheck will add proper handling of noreturn attributes.

**Pull request closed without merging**
