### PR TITLE
Running multiple cpus

### PR DESCRIPTION
**Pull request by parth-27**
Added option to run multiple cpus in ew.py

### CODE REVIEW

**Comment by le-jzr** [comment]
Hi. It's not clear what you are actually changing since you reformatted the whole file. Also, it seems like only the first commit is supposed to be in this pull request.

**Comment by parth-27** [comment]
> Hi. It's not clear what you are actually changing since you reformatted the whole file. Also, it seems like only the first commit is supposed to be in this pull request.

I have added command line option(-smp cpus=n) for running multiple cpus in ew.py

**Comment by vhotspur** [comment]
> > Hi. It's not clear what you are actually changing since you reformatted the whole file. Also, it seems like only the first commit is supposed to be in this pull request.
> 
> I have added command line option(-smp cpus=n) for running multiple cpus in ew.py

Yes. But the diff is completely unreviewable (i.e. it is impossible see the actual change in the mist of changed indenting). If you wish to reformat the file, do so in a separate PR, please.

The same goes for adding other commands - open a separate PR for each of these (i.e. create a new branch from HelenOS's `master` for each of new commands).

I would say the this PR is in current state unmergeable and completely new PRs shall be opened.

**Comment by parth-27** [comment]
Okay I will create a new PRs.

> > > Hi. It's not clear what you are actually changing since you reformatted the whole file. Also, it seems like only the first commit is supposed to be in this pull request.
> > 
> > 
> > I have added command line option(-smp cpus=n) for running multiple cpus in ew.py
> 
> Yes. But the diff is completely unreviewable (i.e. it is impossible see the actual change in the mist of changed indenting). If you wish to reformat the file, do so in a separate PR, please.
> 
> The same goes for adding other commands - open a separate PR for each of these (i.e. create a new branch from HelenOS's `master` for each of new commands).
> 
> I would say the this PR is in current state unmergeable and completely new PRs shall be opened.

Okay i will create new PRs

**Pull request closed without merging**
