### PR TITLE
Fix memory leaks in nic_wol_virtue_add_impl procedure by free virtue variable.

### PR DESCRIPTION
**Pull request by manux81**

### CODE REVIEW

**Comment by le-jzr** [comment]
Don't we also need to free `virtue->data`?

**Comment by manux81** [comment]
Yes, you are right! but when length is equal to zero I can't free virtual->data field. What do you think to move down "if (length != 0)" block?

**Comment by le-jzr** [comment]
> but when length is equal to zero I can't free virtual->data field.

That is not actually true. In that case the field is `NULL`, and `free(NULL)` is a no-op.

**Comment by manux81** [comment]
Ok

**Comment by manux81** [comment]
Fixed

**Comment by le-jzr** [comment]
Thanks!

**Pull request merged**
